// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPCctwzjmBcc-p3UQugsE4K24g-1AhUqg',
    appId: '1:614759105573:web:3083dedd712e8970966bcc',
    messagingSenderId: '614759105573',
    projectId: 'kelana-f39b1',
    authDomain: 'kelana-f39b1.firebaseapp.com',
    storageBucket: 'kelana-f39b1.firebasestorage.app',
    measurementId: 'G-T7F3RJKE2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA28HZuw8HfdjsDdOAMmt7-BjiaSX32TFI',
    appId: '1:614759105573:android:14e472b63fc12784966bcc',
    messagingSenderId: '614759105573',
    projectId: 'kelana-f39b1',
    storageBucket: 'kelana-f39b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMVc9WFMRUhybAkwCMoI4DuR87mE0oyB0',
    appId: '1:614759105573:ios:2e3dc5266d0d9205966bcc',
    messagingSenderId: '614759105573',
    projectId: 'kelana-f39b1',
    storageBucket: 'kelana-f39b1.firebasestorage.app',
    iosBundleId: 'com.example.kelanaApp',
  );
}
